### PR TITLE
Remove package-lock.json

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes `package-lock.json`.  The readme states that we should be using Yarn.

### CODE REVIEW

**Comment by caugner** [comment]
> This PR removes `package-lock.json`. The readme states that we should be using Yarn.

Let's migrate this repo to npm and update the docs, actually. 🙃

**Comment by caugner** [comment]
@queengooborg FYI Your commit has "Unverified" status.

**Comment by queengooborg** [comment]
Ah- I was trying GitHub Codespaces to make this PR without locally cloning the repository, I'm surprised that it didn't sign my commits!

**Comment by queengooborg** [comment]
Closing in favor of #119.

**Pull request closed without merging**
