### PR TITLE
Migrate from Yarn to NPM

### PR DESCRIPTION
**Pull request by queengooborg**
This PR migrates the repository from Yarn to NPM, removing the `yarn.lock` and updating the readme to mention NPM commands in place of Yarn commands.

### CODE REVIEW

**Review by caugner — APPROVED** [review]
🎉

**Comment by bsmth** [comment]
I couldn't get this to build. I've checked in some changes on the following branch that fix the issues you get when running `npm run serve` : https://github.com/mdn/release-dashboard/tree/fix-serve

**Comment by caugner** [comment]
> I couldn't get this to build.

For me, `yarn install` fails on `main` with the following error:

```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.12.1"
error Found incompatible module.
```

On the other hand, `npm install` works on `main`, but then `npm serve` fails with the following error message:

```
% npm run serve                                                                                1 ↵ ✹

> release-dashboard@0.1.0 serve
> vue-cli-service serve

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 INFO  Starting development server...
10% building 2/3 modules 1 active ...ref--14-0!/Users/claas/github/mdn/release-dashboard/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/claas/github/mdn/release-dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/claas/github/mdn/release-dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active ...lient/index.js?http://192.168.178.48:8080&sockPath=/sockjs-nodenode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/claas/github/mdn/release-dashboard/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/claas/github/mdn/release-dashboard/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/claas/github/mdn/release-dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/claas/github/mdn/release-dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/claas/github/mdn/release-dashboard/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

But indeed, @bsmth's `fix-serve` branch works for me locally (both `npm install` and `npm run serve`).

**Comment by caugner** [comment]
@bsmth I think the broken install/serve is unrelated to `npm`, so I would suggest to merge this PR (just needs another `rm package-lock.json yarn.lock && npm install` to resolve the conflict).

**Comment by bsmth** [comment]
Sounds good to me, feel free to merge and we can look at the other bits in a follow up

**Pull request merged**
